export const weatherImages = {
  'Partly cloudy': require('../Assets/partlycloudy.png'),
  'Moderate rain': require('../Assets/moderaterain.png'),
  'Patchy rain possible': require('../Assets/moderaterain.png'),
  'Sunny': require('../Assets/sun.png'),
  'Clear': require('../Assets/sun.png'),
  'Overcast': require('../Assets/cloud.png'),
  'Cloudy': require('../Assets/cloud.png'),
  'Light rain': require('../Assets/moderaterain.png'),
  'Moderate rain at times': require('../Assets/moderaterain.png'),
  'Heavy rain': require('../Assets/heavyrain.png'),
  'Heavy rain at times': require('../Assets/heavyrain.png'),
  'Moderate or heavy freezing rain': require('../Assets/heavyrain.png'),
  'Moderate or heavy rain shower': require('../Assets/heavyrain.png'),
  'Moderate or heavy rain with thunder': require('../Assets/heavyrain.png'),
  'Mist': require('../Assets/mist.png'),
  'other': require('../Assets/moderaterain.png'),
};
